"""C++ Engine Bridge.

This module provides the translation layer between our Pydantic `TimelineIR`
and the native C++ `engine_py` structs generated by Pybind11.
"""

from __future__ import annotations

import logging
from typing import Any

from app.schemas.ir import TimelineIR, TrackIR, ClipIR, ExportSettingsIR
import app.core.engine_py as engine_py

logger = logging.getLogger(__name__)


class TimelineBuilder:
    """Utility class to bridge Pydantic IR schema to the C++ Engine structures."""

    @staticmethod
    def build_native_timeline(ir: TimelineIR) -> engine_py.Timeline:
        """Converts a entire TimelineIR object into its C++ equivalent."""
        
        logger.info(f"Building native C++ Timeline for {ir.project_name} (ID: {ir.id})")
        
        native_timeline = engine_py.Timeline(str(ir.id), ir.project_name)

        for track_ir in ir.tracks:
            native_track = TimelineBuilder._build_native_track(track_ir)
            native_timeline.add_track(native_track)

        return native_timeline

    @staticmethod
    def build_native_export_config(ir: ExportSettingsIR) -> engine_py.ExportConfig:
        """Converts ExportSettingsIR into C++ ExportConfig."""
        config = engine_py.ExportConfig()
        config.format = ir.format.value
        config.resolution = ir.resolution.value
        config.codec = ir.codec.value
        config.frame_rate = float(ir.frame_rate)
        config.bitrate_kbps = ir.bitrate_kbps
        config.output_path = str(ir.output_path)
        return config

    @staticmethod
    def _build_native_track(ir: TrackIR) -> engine_py.Track:
        # Match enum strings to C++ enums if required (engine_py.TrackType)
        if ir.type.value == "video":
            track_type_enum = engine_py.TrackType.Video
        elif ir.type.value == "audio":
            track_type_enum = engine_py.TrackType.Audio
        else:
            track_type_enum = engine_py.TrackType.Subtitle

        native_track = engine_py.Track(str(ir.id), track_type_enum, ir.name)
        native_track.set_muted(ir.muted)
        native_track.set_locked(ir.locked)
        native_track.set_opacity(ir.opacity)

        for clip_ir in ir.clips:
            native_clip = TimelineBuilder._build_native_clip(clip_ir)
            native_track.add_clip(native_clip)

        return native_track

    @staticmethod
    def _build_native_clip(ir: ClipIR) -> engine_py.Clip:
        native_clip = engine_py.Clip(
            str(ir.id),
            str(ir.source_path),
            float(ir.in_point),
            float(ir.out_point)
        )
        native_clip.set_position(float(ir.position))
        native_clip.set_playback_speed(float(ir.playback_speed))
        native_clip.set_volume(float(ir.volume))

        # Add Effects mapped to native struct
        for effect_ir in ir.effects:
            native_effect = engine_py.Effect()
            native_effect.id = str(effect_ir.id)
            native_effect.type = effect_ir.type.value
            native_effect.start_time = float(effect_ir.start_time)
            if effect_ir.duration is not None:
                 native_effect.duration = float(effect_ir.duration)
            native_effect.parameters = effect_ir.parameters
            # Not fully supported array conversion right now if missing binds,
            # but standard dict/list casting via pybind11 is active
            native_clip.add_effect(native_effect)

        return native_clip
